### PR TITLE
This script bruteforced subdomains even when a wildcard existed. The incredible solution this developer found will bring you to tears!

### PR DESCRIPTION
**Pull request by DatDraggy**
From issue #27 
I couldn't test the whole thing, because I always got a "IP address does not appear to be within Cloudflare range, shutting down.. " error recently, even though it says Server IP: 104.31.91.191 and is a fresh clone from the original repo.

It should work without problems. I tested the function separately.

### CODE REVIEW

**Comment by DatDraggy** [comment]
I was able to test it now. Works perfectly 👍 
Optionally, I could add the time at the beginning and color the text but I personally think it looks better like this because it shows the user it's waiting on a action.

**Comment by DatDraggy** [comment]
Merge please?

**Comment by m0rtem** [comment]
@DatDraggy I will review this this week for you, apologies it has taken more than a year

**Comment by DatDraggy** [comment]
No problemo

**Comment by DatDraggy** [comment]
Two new commits. Either replace \n with space on line 33 in dumpsterapi or revert changes in the print_out method. I personally prefer option B, but A also has it's perks as it further seperates details.

**Comment by DatDraggy** [comment]
Actually, because the screenshot shows how A would show it, let's just go with that.

**Comment by DatDraggy** [comment]
I reviewed and decided to just go with this. Makes it easier to merge the other pull request.

**Review by m0rtem — APPROVED** [review]

**Comment by m0rtem** [comment]
Good work mate, sorry it took so long for me to merge in.

**Pull request merged**
